[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Lighthouse = "ac2c24cd-07f0-4848-96b2-1b82c3ea0e59"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[compat]
Documenter = "1.3"
StableRNGs = "1"

[sources]
Lighthouse = {path = ".."}
